---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
  labels:
    provider: "fabric8"
    project: "test"
    version: "0.0.1-SNAPSHOT"
    group: "test"
  name: "test"
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "test"
    provider: "fabric8"
    group: "test"
  type: "LoadBalancer"
