---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    labels:
      provider: "fabric8"
      project: "test"
      version: "0.0.1-SNAPSHOT"
      group: "test"
    name: "test"
  spec:
    ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "test"
      provider: "fabric8"
      group: "test"
    type: "LoadBalancer"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=test&var-version=0.0.1-SNAPSHOT"
    labels:
      provider: "fabric8"
      project: "test"
      version: "0.0.1-SNAPSHOT"
      group: "test"
    name: "test"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "test"
        provider: "fabric8"
        group: "test"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/spring-boot.svg"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=test&var-version=0.0.1-SNAPSHOT"
        labels:
          provider: "fabric8"
          project: "test"
          version: "0.0.1-SNAPSHOT"
          group: "test"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "test/test:latest"
          imagePullPolicy: "IfNotPresent"
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          securityContext:
            privileged: false
